[package]
name = "dotmanager"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dm"
path = "src/main.rs"

[dependencies]
bincode = "1.3.3"
color-print = "0.3.5"
dialoguer = "0.11.0"
dirs = "5.0.1"
once_cell = "1.19.0"
prettytable-rs = "0.10.0"
